import React from 'react'
import { Typography, Box, TextField } from '@mui/material';

const Quesbar1 = (activeStep) => {

    return (
        <div>
            <Typography sx={{ mt: 10, mb: 1, pl: 7, fontWeight: 9000, fontSize: '2.1rem' }}>
                Step 1: General Questions
            </Typography>

            <Box>
                <Typography sx={{ mt: 5, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.7rem' }}>
                    Question 1
                </Typography>

                <Typography sx={{ mt: 2, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.2rem' }}>
                    generated by AI
                </Typography>

                <Box
                    component="form"
                    sx={{pl: 6,
                        '& .MuiTextField-root': { m: 1, width: '150ch' },
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <div>
                        <TextField
                            id="outlined-multiline-flexible"
                            multiline
                            maxRows={4}
                        />
                    </div>
                </Box>
            </Box>

            <Box>
                <Typography sx={{ mt: 5, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.7rem' }}>
                    Question 2
                </Typography>

                <Typography sx={{ mt: 2, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.2rem' }}>
                    generated by AI
                </Typography>

                <Box
                    component="form"
                    sx={{pl: 6,
                        '& .MuiTextField-root': { m: 1, width: '150ch' },
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <div>
                        <TextField
                            id="outlined-multiline-flexible"
                            multiline
                            maxRows={4}
                        />
                    </div>
                </Box>
            </Box>

            <Box>
                <Typography sx={{ mt: 5, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.7rem' }}>
                    Question 3
                </Typography>

                <Typography sx={{ mt: 2, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.2rem' }}>
                    generated by AI
                </Typography>

                <Box
                    component="form"
                    sx={{pl: 6,
                        '& .MuiTextField-root': { m: 1, width: '150ch' },
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <div>
                        <TextField
                            id="outlined-multiline-flexible"
                            multiline
                            maxRows={4}
                        />
                    </div>
                </Box>
            </Box>

            <Box>
                <Typography sx={{ mt: 5, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.8rem' }}>
                    Question 4
                </Typography>

                <Typography sx={{ mt: 2, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.2rem' }}>
                    generated by AI
                </Typography>

                <Box
                    component="form"
                    sx={{pl: 6,
                        '& .MuiTextField-root': { m: 1, width: '150ch' },
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <div>
                        <TextField
                            id="outlined-multiline-flexible"
                            multiline
                            maxRows={4}
                        />
                    </div>
                </Box>
            </Box>

            <Box>
                <Typography sx={{ mt: 5, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.7rem' }}>
                    Question 5
                </Typography>

                <Typography sx={{ mt: 2, mb: 1, pl: 7, fontWeight: 9000, fontSize: '1.2rem' }}>
                    generated by AI
                </Typography>

                <Box
                    component="form"
                    sx={{pl: 6,
                        '& .MuiTextField-root': { m: 1, width: '150ch' },
                    }}
                    noValidate
                    autoComplete="off"
                >
                    <div>
                        <TextField
                            id="outlined-multiline-flexible"
                            multiline
                            maxRows={4}
                        />
                    </div>
                </Box>
            </Box>

        </div>


    )
}

export default Quesbar1